apiVersion : apps/v1 
kind : Deployment 
metadata:
 name : backend-deployment 
spec :
 replicas : 3 
 selector : 
  matchLabels : 
   app : backend 
 template : 
  metadata :
   labels : 
    app : backend 
  spec :
   containers : 
    - name : backend-container
      image : samandarjumanov0405/video-chat-app 
      ports : 
       - containerPort : 3001
         protocol : TCP
        


