apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: default
  labels:
    app: video-chat-app
    tier: backend
spec:
  ports:
  - protocol: 'TCP'
    port: 3001
    targetPort: 3001
  type: LoadBalancer
